--Câu 29
SELECT MASP, TENSP
FROM SANPHAM
WHERE NUOCSX = 'Thai Lan' AND GIA IN(
	SELECT DISTINCT TOP 3 GIA FROM SANPHAM
	ORDER BY GIA DESC
)
--Câu 30
SELECT MASP, TENSP
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc' AND GIA IN(
	SELECT DISTINCT TOP 3 GIA FROM SANPHAM
	WHERE NUOCSX = 'Trung Quoc'
	ORDER BY GIA DESC
)
--Câu 31
SELECT TOP 3 MAKH, HOTEN
FROM KHACHHANG
ORDER BY DOANHSO DESC
--Câu 32
SELECT COUNT(*) AS TONGSANPHAM
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc'
--Câu 33
SELECT NUOCSX, COUNT(*) AS TONGSANPHAM
FROM SANPHAM
GROUP BY NUOCSX
--Câu 34
SELECT NUOCSX, MAX(GIA) AS GIACAONHAT, MIN(GIA) AS GIATHAPNHAT, AVG(GIA) AS GIATRUNGBINH
FROM SANPHAM
GROUP BY NUOCSX
--Câu 35
SELECT NGHD, SUM(TRIGIA) AS DOANHTHUNGAY
FROM HOADON
GROUP BY NGHD
--Câu 36
SELECT MASP, SUM(SL) AS SOLUONGBANRA 
FROM CTHD CT
JOIN HOADON HD
ON CT.SOHD = HD.SOHD
WHERE MONTH(NGHD) = '10' AND YEAR(NGHD) = '2006'
GROUP BY MASP
--Câu 37
SELECT MONTH(NGHD) AS THANG, SUM(TRIGIA) AS DOANHTHU
FROM HOADON
WHERE YEAR(NGHD) = '2006'
GROUP BY MONTH(NGHD)
--Câu 38
SELECT HD.SOHD 
FROM HOADON HD
JOIN CTHD CT 
ON HD.SOHD = CT.SOHD
GROUP BY HD.SOHD
HAVING COUNT(DISTINCT MASP) >= 4
--Câu 39
SELECT HD.SOHD
FROM HOADON HD
JOIN CTHD CT
ON HD.SOHD = CT.SOHD
JOIN SANPHAM SP
ON CT.MASP = SP.MASP
WHERE NUOCSX = 'Viet Nam'
GROUP BY HD.SOHD
HAVING COUNT(DISTINCT SP.MASP) =3
--Câu 40
SELECT TOP 1 KH.MAKH, KH.HOTEN
FROM KHACHHANG KH
JOIN HOADON HD
ON KH.MAKH = HD.MAKH
GROUP BY KH.MAKH, KH.HOTEN
ORDER BY COUNT(DISTINCT SOHD) DESC
--Câu 41
SELECT TOP 1 MONTH(NGHD) AS THANG, SUM(TRIGIA) AS DOANHTHU 
FROM HOADON
WHERE YEAR(NGHD) = '2006'
GROUP BY MONTH(NGHD)
ORDER BY SUM(TRIGIA) DESC
--Câu 42
SELECT TOP 1 SP.MASP, SP.TENSP 
FROM SANPHAM SP
JOIN CTHD CT
ON SP.MASP = CT.MASP
JOIN HOADON HD
ON CT.SOHD = HD.SOHD
WHERE YEAR(NGHD) = '2006'
GROUP BY SP.MASP, SP.TENSP
ORDER BY SUM(SL) ASC
--Câu 43 
SELECT B.NUOCSX, MASP, TENSP
FROM (SELECT NUOCSX, MAX(GIA) AS MAX
	  FROM SANPHAM
	  GROUP BY NUOCSX) AS B LEFT JOIN SANPHAM S
	  ON S.GIA = B.MAX
WHERE B.NUOCSX = S.NUOCSX
--Câu 44
SELECT NUOCSX
FROM SANPHAM
GROUP BY NUOCSX
HAVING COUNT(DISTINCT GIA) >=3
--Câu 45
SELECT *
FROM KHACHHANG
WHERE MAKH = (SELECT TOP 1 A.MAKH
			  FROM (SELECT TOP 10 MAKH FROM KHACHHANG ORDER BY DOANHSO) AS A
			  LEFT JOIN
			  (SELECT MAKH, COUNT(SOHD) AS SL
			  FROM HOADON
			  GROUP BY MAKH) AS B
			  ON A.MAKH = B.MAKH
			  ORDER BY SL DESC)